### ISSUE TITLE
升级0.6.0问题

### ISSUE THREAD

**Issue by xayoung** [Good0007/Asrock-Z390M-ITX-AC-Hackintosh-OC#1]
0.5.9开始用你的配置
请教下升级0.6.0的流程是直接替换更新的efi文件和驱动，然后重启系统，再升级macOS 10.15.6，还是同时一次性做完这两步操作？

**Comment by Good0007** [comment]
之前的0.5.9 升级到 10.15.6都没问题的，如果没问题可以不用升级0.6.0，升级的话建议是先修改0.6.0里面的config.plist 把你原来的序列号替换进去，然后直接用0.6.0的EFI替换现在用的
